version: "3"

services:
  php:
    container_name: learn-programming-php
    build:
      context: ./php
    ports:
      - 8080:80
    volumes:
      - ../htdocs:/var/www/html
    restart: always
  db:
    container_name: learn-programming-mysql
    image: mysql:8.0.23
    volumes:
      - mysql_data_volume:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
volumes:
  mysql_data_volume:
    name: learn-programming-mysql-volume